[package]
name = "day-5"
version = "0.1.0"
authors = ["Alex Cole <git@y-less.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scan_fmt = "0.2.5"
regex = "1.4.2"
