[package]
name = "d13b"
version = "0.1.0"
authors = ["Y_Less <git@y-less.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#ncurses-rs = "*"
winapi = "0.2.8"
kernel32-sys = "0.2.1"
